POST http://localhost:3000/V6/Varshita/MastersAddOns/Alter/3
Content-Type: application/json

{
    "AddOnService": "TOUGH OIL STAINS",
    "AddOnRate": "150",
    "UuId": 3,
    "pk": 3,
    "DateTime": "2025-01-07T12:22:47.281Z"
  }