POST http://localhost:3000/Masters/MastersAddOns/Alter/56
Content-Type: application/json

{
  "AddOnService": "Doubled STAINS",
    "AddOnRate": "5",
    "UuId": 56,
    "pk": 56,
    "DateTime": "2025-01-20T07:27:16.655Z"
}